### PR TITLE
Soubar city fix/compatibility with oBG2.

### PR DESCRIPTION
**Pull request by Roberciiik**
- Restored AR4230 Soubar MOS file for oBG2. It has correct size now.
- Fountain crash is fixed by restoring Beregost AR4230 TIS file, however custom Soubar's obelisk shows "Beregost" now instead of "Soubar". I checked that the same trade-off was applied for PVRZ-based TIS files for EE.

### CODE REVIEW

**Comment by Gitjas** [comment]
The PR saying it restored WED file contains a MOS file, though?
What do you mean with trade-off for TIS?

**Comment by Roberciiik** [comment]
> The PR saying it restored WED file contains a MOS file, though?

You're right, I just replaced MOS file. (I thought it will be WED file.) I will edit the description.


> What do you mean with trade-off for TIS?

Modification provided slightly edited Beregost map (has obelisk with "Soubar" name in the city center). However, the fountain is broken. So I restored original Beregost TIS file (same as it is done in EE). Hence, there is no more Soubar obelisk (this is the trade-off).
image

**Review by ALIENQuake — APPROVED** [review]

**Comment by ALIENQuake** [comment]
I'm fine with this tradeoff because it fixes the crash. Someday someone else can improve the fountain.

**Comment by Gitjas** [comment]
Yes, cool. The inscription "Soubar" on the trigger point could be patched via tp2, it's not difficult, just needs to be inserted. Example code from Seatower mod:
`	COPY ~bst/areas/ys0118/ys0118.are~ ~override/ys0118.are~
	SAY 0x244 @26`

**Comment by Gitjas** [comment]
The info text for trigger points would be in the are-file though, which wasn't changed? *scratches head*

**Pull request merged**
